### PR TITLE
Allow numbers between 8 and 15 characters/localizations for German/Italian

### PR DESCRIPTION
**Pull request by clementzach**
This PR sets a min and max number for phone numbers rather than requiring them to be at least 15 characters long. 

I also added localization files for German and Italian.

The app worked correctly on the Android emulator on my machine, and researchers haven't had issues with the screenshots I've sent them.

### CODE REVIEW

**Comment by clementzach** [comment]
@zagorsky, I talked with @kwcarlso and she said that our lab would love to have you merge this PR and deploy a new version of the app. 

These changes need to go to the version of the app hosted at http://eu.beiwe.org/download in particular, because that is the deployment that study participants using these features will use to download the app.

**Comment by biblicabeebli** [comment]
@zagorsky I see no reason not to merge this in.  I've checked and there are no conflicts with the jz/messaging branch, is there localization work on that that will need to be added?

**Comment by clementzach** [comment]
I believe that it would be better for us to merge this now and have non-localized messaging text than to wait until the messaging feature is done to localize this. The German team hopes to start recruiting in the next week or so, and it would be nice for them to be able to have a localized version of the app from the get-go

**Review by zagorsky — APPROVED** [review]
I tested this on my Android 9, and the Beiwe app correctly displays in German or Italian if you set the phone's primary language to German or Italian.  I also tested the phone number validation.

**Pull request merged**
